coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "examples/*"
  - "docs/*"
  - "setup.py"
  - "energyunits.egg-info/*"

flags:
  unittests:
    paths:
      - energyunits/